### ISSUE TITLE
Instructions for install?

### ISSUE THREAD

**Issue by maryawood** [sa-lee/superintronic#2]
Hello, I'm trying to install superintronic, but have been running into issues. I've been using devtools to install from this repo, as superintronic doesn't appear to be available through CRAN or Bioconductor:

`install_github('sa-lee/superintronic')`

This gives me the follow error message:

`ERROR: dependency ‘plyranges’ is not available for package ‘superintronic’`

I've tried installing plyranges both via Bioconductor and from source. The version that gets install via Bioconductor (`BiocManager::install("plyranges")`) is incompatible with superintronic (1.2.0, while superintronic requires 1.7.14), and installing from source the file available on the Bioconductor website (`install.packages('plyranges_1.10.0.tar.gz', repos=NULL, type="source")`) gives the following error:

`Error : object ‘%in%’ is not exported by 'namespace:BiocGenerics'`

Do you have any advice on how to get around these hurdles? I am using R version 3.5.1 via anaconda.

Thanks!

**Comment by sa-lee** [comment]
Hi there!

First, you can use `BiocManager` to install Bioc related packages from github: `BiocManager::install("sa-lee/superintronic")`.

What version of Bioconductor are you using? What does `BiocManager::version()` give? The current release version of `plyranges` should be compatible with `superintronic, however, you might also need to upgrade your R version to be compatible with latest Biocondcutor.

Thanks,
Stuart

**Comment by maryawood** [comment]
Hi, thank you for this information! I was working with the default R/Bioconductor versions available using Anaconda. Updating to R version 4.0.1 and installing Bioconductor and superintronic from there seems to have solved the problem. These requirements would probably be good to have listed in the README.

**Comment by sa-lee** [comment]
Noted, thanks for the feedback! I really should get the package on bioconductor
